# Generated by Django 3.2.5 on 2021-12-27 12:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Outsider',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=30)),
                ('spouse_first_name', models.CharField(max_length=30)),
                ('spouse_last_name', models.CharField(max_length=30)),
                ('spouse_number', models.CharField(max_length=30)),
                ('home_address', models.CharField(max_length=100)),
                ('is_member', models.BooleanField()),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.members')),
            ],
            options={
                'unique_together': {('id', 'sponsor')},
            },
        ),
        migrations.CreateModel(
            name='Outsider_Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_reviewed', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan_amount', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Outsider_Repayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_repaid', models.PositiveBigIntegerField()),
                ('date_repaid', models.DateTimeField(default=django.utils.timezone.now)),
                ('loan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='non_members.outsider_loan')),
            ],
        ),
        migrations.CreateModel(
            name='Unpaid',
            fields=[
                ('repayment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='non_members.outsider_repayment')),
                ('balance', models.PositiveBigIntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Outsider_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_requested', models.DateTimeField(default=django.utils.timezone.now)),
                ('amount_requested', models.PositiveBigIntegerField()),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.members')),
                ('outsider', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='non_members.outsider')),
            ],
        ),
        migrations.AddField(
            model_name='outsider_loan',
            name='outsider_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='non_members.outsider_request'),
        ),
    ]
