# Generated by Django 3.2.5 on 2021-12-27 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('non_members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unpaid',
            name='repayment',
        ),
        migrations.AddField(
            model_name='unpaid',
            name='member_loan',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='non_members.outsider_loan'),
            preserve_default=False,
        ),
    ]
