# Generated by Django 3.2.5 on 2021-12-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='outsider',
            old_name='Last_name',
            new_name='last_name',
        ),
    ]
