# Generated by Django 3.2.5 on 2021-12-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_members', '0002_auto_20211227_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outsider',
            name='is_member',
        ),
    ]
