# Generated by Django 3.2.5 on 2021-12-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('non_members', '0003_alter_unpaid_lb_balance'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='outsider',
            unique_together={('first_name', 'username')},
        ),
    ]
