# Generated by Django 3.2.5 on 2021-12-30 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unpaid',
            name='interest',
        ),
    ]
