# Generated by Django 3.2.5 on 2021-12-19 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member_loan',
            old_name='Member_Request',
            new_name='member_request',
        ),
        migrations.RenameField(
            model_name='members',
            old_name='Last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='unpaid',
            old_name='Member_Repayment',
            new_name='member_repayment',
        ),
    ]
