# Generated by Django 3.2.5 on 2021-12-27 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='is_member',
        ),
        migrations.RemoveField(
            model_name='members',
            name='share_value',
        ),
    ]
