# Generated by Django 3.2.5 on 2021-12-30 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_unpaid_interest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unpaid',
            name='lb_balance',
            field=models.BigIntegerField(),
        ),
    ]
