# Generated by Django 3.2.5 on 2021-12-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20211227_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member_loan',
            name='request_status',
        ),
    ]
